### ISSUE TITLE
pip 8.0.2 can't install/update packages on Windows (virtualenv)

### ISSUE THREAD

**Issue by izaimo** [pypa/virtualenv#871]
After upgrading from pip7.1.2 to 8.0.2, I get this error when I try to update any package like (django, setuptools, wheel etc.) also I can't even "pip freeze" on **virtualenv**. Globally there are no problems.

> Error: Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 5\helpers\packaging_tool.py", line 56, in do_install
    import pip
  File "C:\Users\Master\Env\Django-Blog\lib\site-packages\pip\__init__.py", line 14, in <module>
    from pip.baseparser import ConfigOptionParser, UpdatingDefaultsHelpFormatter
  File "C:\Users\Master\Env\Django-Blog\lib\site-packages\pip\baseparser.py", line 13, in <module>
    from pip.locations import (
  File "C:\Users\Master\Env\Django-Blog\lib\site-packages\pip\locations.py", line 12, in <module>
    from pip.utils import appdirs
  File "C:\Users\Master\Env\Django-Blog\lib\site-packages\pip\utils\__init__.py", line 22, in <module>
    from pip.locations import (
ImportError: cannot import name site_packages

PS. It tries to import **site_packages** while my folder name was by default **site-packages** and worked like a charm on pip7.1.2.

Same from Command Prompt:

> (Django-Blog) C:\Users\Master\Env\Django-Blog>pip freeze
Traceback (most recent call last):
  File "C:\Users\Master\Env\Django-Blog\Scripts\pip-script.py", line 9, in <module>
    load_entry_point('pip==8.0.2', 'console_scripts', 'pip')()
  File "c:\users\master\env\django-blog\lib\site-packages\pkg_resources\__init__.py", line 547, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\master\env\django-blog\lib\site-packages\pkg_resources\__init__.py", line 2710, in load_entry_point
    return ep.load()
  File "c:\users\master\env\django-blog\lib\site-packages\pkg_resources\__init__.py", line 2370, in load
    return self.resolve()
  File "c:\users\master\env\django-blog\lib\site-packages\pkg_resources\__init__.py", line 2376, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\master\env\django-blog\lib\site-packages\pip\__init__.py", line 14, in <module>
    from pip.baseparser import ConfigOptionParser, UpdatingDefaultsHelpFormatter
  File "c:\users\master\env\django-blog\lib\site-packages\pip\baseparser.py", line 13, in <module>
    from pip.locations import (
  File "c:\users\master\env\django-blog\lib\site-packages\pip\locations.py", line 12, in <module>
    from pip.utils import appdirs
  File "c:\users\master\env\django-blog\lib\site-packages\pip\utils\__init__.py", line 22, in <module>
    from pip.locations import (
ImportError: cannot import name site_packages

**Comment by Ivoz** [comment]
Could you file with [pip](pypa/pip), please.

**Comment by Ivoz** [comment]
Ah, tracking [#3482](https://github.com/pypa/pip/issues/3482)

**Comment by izaimo** [comment]
Sure!
