### ISSUE TITLE
ImportError: cannot import name 'get_runnable_pip' from 'pip._internal.utils.misc' (v21.7.1 - pip-26.1.2)

### ISSUE THREAD

**Issue by Lenzerheide** [pypa/virtualenv#3205]
**Steps to reproduce:**

install + activate venv 1 - everything works fine
deactivate
same shell /docker:
install + try to activate venv2 - installation is broken

**Result**

venv2:
ImportError: cannot import name 'get_runnable_pip' from 'pip._internal.utils.misc' 

**Expected**

venv prompt

**Traceback**

```
Traceback (most recent call last):
  File "/builds/company/backend/myapp/BUILD/myapp-0.0.0/venv.docker/audit.venv/bin/pip", line 6, in <module>
    sys.exit(main())
             ^^^^^^
  File "/builds/company/backend/myapp/BUILD/myapp-0.0.0/venv.docker/audit.venv/lib/python3.11/site-packages/pip/_internal/cli/main.py", line 47, in main
    from pip._internal.cli.autocompletion import autocomplete
  File "/builds/company/backend/myapp/BUILD/myapp-0.0.0/venv.docker/audit.venv/lib/python3.11/site-packages/pip/_internal/cli/autocompletion.py", line 12, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/builds/company/backend/myapp/BUILD/myapp-0.0.0/venv.docker/audit.venv/lib/python3.11/site-packages/pip/_internal/cli/main_parser.py", line 11, in <module>
    from pip._internal.build_env import get_runnable_pip
  File "/builds/company/backend/myapp/BUILD/myapp-0.0.0/venv.docker/audit.venv/lib/python3.11/site-packages/pip/_internal/build_env/__init__.py", line 8, in <module>
    from pip._internal.build_env.installer import (
  File "/builds/company/backend/myapp/BUILD/myapp-0.0.0/venv.docker/audit.venv/lib/python3.11/site-packages/pip/_internal/build_env/installer.py", line 22, in <module>
    from pip._internal.utils.misc import get_runnable_pip
ImportError: cannot import name 'get_runnable_pip' from 'pip._internal.utils.misc' (/builds/company/backend/myapp/BUILD/myapp-0.0.0/venv.docker/audit.venv/lib/python3.11/site-packages/pip/_internal/utils/misc.py)
```

**More Information**

Works with v21.7.0 - pip-26.1.2
Also works with v21.7.1 and pip-26.2.1

Seems that v21.7.1 strictly requires pip-26.2.x. 

**Possible Solution**

fix for pip-26.1.2 and older or add pip-26.2.x to requirements

**Comment by gaborbernat** [comment]
This seems a pip or venv bug not vritualenv. Please post docker build that reproduces it.

**Comment by Lenzerheide** [comment]
Spent some time for RCA.

Possible root cause: 

- virtualenv seeded pip 26.2 via app-data
- running `pip install --ignore-installed pip==26.1.2` using the full requirements list results in a mixed/corrupted pip installation—not necessarily a pure virtualenv issue, but reproducible for you

As requested, attached is a minimal setup to reproduce the issue.

- unpack
- enter repro/virtualenv-pip
- ./run-repro.sh --download-wheels  # only once to get wheels for testing
- ./run-repro.sh

[reproduce_virtualenv_3205.tar.gz](https://github.com/user-attachments/files/30789991/reproduce_virtualenv_3205.tar.gz)

**Comment by pfmoore** [comment]
FWIW, this wouldn't be considered a bug by pip either - this is simply a consequence of partially overwriting your pip installation as a result of using `--ignore-installed`.

Essentially, this is a result of user error creating a corrupted pip installation.

**Comment by Lenzerheide** [comment]
THX a lot. You're right: `--ignore-installed` no longer makes sense here; it's an artifact of a previous workflow.
