### ISSUE TITLE
For Ver16.0 Can not working with Jython 2.7.1 on windows

### ISSUE THREAD

**Issue by arrowwind** [pypa/virtualenv#1211]
Can not work with Jython 2.7.1 on windows . 
Error Message: 'module' object has no attribute 'symlink'

I have changed the Jython2.7.1 is Lib\os.py file, add the symlink function. But it's still not working. The files in \bin fold which are copied are not right.

Please fix it. Thank you.

**Comment by gaborbernat** [comment]
Can you validate this still is an issue with master?

**Comment by gaborbernat** [comment]
Closing due to no activity.
