### ISSUE TITLE
Can't get virtualenv to work with python3.6 on a raspberry pi

### ISSUE THREAD

**Issue by HyperEpsilon** [pypa/virtualenv#1944]
**Issue**
I can't get virtualenv to create a virtual environment of python3.6 on my freshly installed raspios lite install.

The latest raspios comes with both python 2.7.16 and 3.7.3, both of which are able to create a virtualenv just fine. However, when I try and run ```virtualenv -p /usr/bin/python3.6 venv``` I am treated with this RuntimeError

```
RuntimeError: failed to query /usr/bin/python3.6 with code 1 err: 'Traceback (most recent call last):\n  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/discovery/py_info.py", line 16, in <module>\n    from distutils import dist\nImportError: cannot import name \'dist\'\n'
```

This is a freshly installed OS and freshly installed version of python 3.6.8 that I compiled from source. I have ensured that I have the latest version of virtualenv. Even when I run the specific 3.6 version with ```python3.6 -m virtualenv -p /usr/bin/python3.6``` I still get the same error
```
RuntimeError: failed to query /usr/bin/python3.6 with code 1 err: 'Traceback (most recent call last):\n  File "/usr/local/lib/python3.6/site-packages/virtualenv/discovery/py_info.py", line 16, in <module>\n    from distutils import dist\nImportError: cannot import name \'dist\'\n'
```

I am able to use python3.6 just fine as far as I can tell.

**Environment**

Provide at least:
- OS: 2020-08-20-raspios-buster-armhf-lite - Freshly installed
- ``pip list`` of the host python where ``virtualenv`` is installed:
    
```
Package             Version
------------------- -------
appdirs             1.4.4
distlib             0.3.1
filelock            3.0.12
fish                1.1
importlib-metadata  1.7.0
importlib-resources 3.0.0
pip                 18.1
setuptools          40.6.2
six                 1.15.0
virtualenv          20.0.31
zipp                3.1.0
```

**Output of the virtual environment creation**

Make sure to run the creation with `-vvv --with-traceback`:

```1947 setup logging to NOTSET [DEBUG report:43]
2272 find interpreter for spec PythonSpec(path=/usr/bin/python3.6) [INFO builtin:44]
2290 Attempting to acquire lock 3051954000 on /home/pi/.local/share/virtualenv/py_info/1/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [DEBUG filelock:270]
2293 Lock 3051954000 acquired on /home/pi/.local/share/virtualenv/py_info/1/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [INFO filelock:274]
2301 get interpreter info via cmd: /usr/bin/python3.6 /home/pi/.local/lib/python3.7/site-packages/virtualenv/discovery/py_info.py [DEBUG cached_py_info:87]
3621 Attempting to release lock 3051954000 on /home/pi/.local/share/virtualenv/py_info/1/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [DEBUG filelock:315]
3625 Lock 3051954000 released on /home/pi/.local/share/virtualenv/py_info/1/30295c5bec572e859485b1ffa5e89b8b3e2022ef6e3e739c1ac40f143a557caf.lock [INFO filelock:318]
Traceback (most recent call last):
  File "/home/pi/.local/bin/virtualenv", line 10, in <module>
    sys.exit(run_with_catch())
  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/__main__.py", line 62, in run_with_catch
    run(args, options)
  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/__main__.py", line 16, in run
    session = cli_run(args, options)
  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/run/__init__.py", line 26, in cli_run
    of_session = session_via_cli(args, options, setup_logging)
  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/run/__init__.py", line 42, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging)
  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/run/__init__.py", line 64, in build_parser
    parser._interpreter = interpreter = discover.interpreter
  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/discovery/discover.py", line 44, in interpreter
    self._interpreter = self.run()
  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/discovery/builtin.py", line 33, in run
    return get_interpreter(self.python_spec, self.app_data)
  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/discovery/builtin.py", line 46, in get_interpreter
    for interpreter, impl_must_match in propose_interpreters(spec, app_data):
  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/discovery/builtin.py", line 66, in propose_interpreters
    yield PythonInfo.from_exe(os.path.abspath(spec.path), app_data), True
  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/discovery/py_info.py", line 315, in from_exe
    proposed = from_exe(cls, app_data, exe, raise_on_error=raise_on_error, ignore_cache=ignore_cache)
  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/discovery/cached_py_info.py", line 31, in from_exe
    raise result
RuntimeError: failed to query /usr/bin/python3.6 with code 1 err: 'Traceback (most recent call last):\n  File "/home/pi/.local/lib/python3.7/site-packages/virtualenv/discovery/py_info.py", line 16, in <module>\n    from distutils import dist\nImportError: cannot import name \'dist\'\n'


```

**Comment by HyperEpsilon** [comment]
After reading through some other issues, https://github.com/pypa/virtualenv/issues/1643, I found a link to the [documentation](https://virtualenv.pypa.io/en/latest/user_guide.html#python-discovery).

Reading through the section on python-discovery made me realize I don't need to specify a path.

` virtualenv -p python3.6 venv` works just fine
