### ISSUE TITLE
ImportError: cannot import name 'install_wheel' from 'virtualenv'

### ISSUE THREAD

**Issue by marcom-db** [pypa/virtualenv#2038]
The following command `from virtualenv import install_wheel` worked on virtualenv 16.7.10

After upgrading to 20.2.2 I get the following error: 
`ImportError: cannot import name 'install_wheel' from 'virtualenv'`

It seems install_wheel is no longer included in the 20.x release. Any ideas on how to fix this?

**Comment by gaborbernat** [comment]
> It seems install_wheel is no longer included in the 20.x release. Any ideas on how to fix this?

Depends. What do you want to do?

**Comment by marcom-db** [comment]
Thanks @gaborbernat. I am trying to lazily install pip, after creation of the virtualenv: `install_wheel(['pip'], 'path/to/python')`

**Comment by gaborbernat** [comment]
Can you please expand on the use case? Why the need to be lazy? What python versions? What platform? Etc.

**Comment by marcom-db** [comment]
The platform is ubuntu 18.04. The Version of python is 3.8. The version of virtualenv is 20.2.2.

The use case is that I have created a virtualenv with the flag `--no-pip`. Now I would like to install pip in the virtualenv. The reason I wait to install pip until I need it is performance.

**Comment by gaborbernat** [comment]
Please expand further, on what performance benefits, why needed? I want the entire story not just the top shell of it to best assist you.

**Comment by marcom-db** [comment]
Hey Gabor, Thanks for following up. I appreciate your help here.

I use virtualenv to manage python environments of many users. When a user creates an account on my cluster I create a virtualenv for them. I want them to be able to start using their account as quickly as possible, so any time I can save in initializing the virtualenv is valuable. That is why I pass the flag `--no-pip`. Once the user wants to install a new python package in their virtualenv, then I install pip in the virtualenv so that they can install the package. 

Previously I used `install_wheel` to install pip. Now I am looking for an alternative to `install_wheel`.

I hope this is more clear and helps.

**Comment by pfmoore** [comment]
You can install pip using `get-pip.py` as described [here](https://pip.pypa.io/en/latest/installing/#installing-with-get-pip-py).

**Comment by gaborbernat** [comment]
> You can install pip using `get-pip.py` as described [here](https://pip.pypa.io/en/latest/installing/#installing-with-get-pip-py).

Yes, though I'd not recommend that, because you'll be taking the slow path of getting this done, see https://virtualenv.pypa.io/en/latest/user_guide.html#seeders for more information on the pip vs app-data mode.

99% of a virtual environment creation time is installing the wheels. So the cleanest solution I'd recommend is to just recreate the virtual environment whenever the user first invokes pip. You can just invoke the virtualenv command again without the ``--no-pip`` flag.

**Comment by marcom-db** [comment]
Thanks pfmoore. I'm going to close this issue.
