### ISSUE TITLE
site.getsitepackages() missing

### ISSUE THREAD

**Issue by wichert** [pypa/virtualenv#737]
The standard [site.getsitepackages()](https://docs.python.org/2/library/site.html#site.getsitepackages) function is not available in a virtualenv:

``` python
>>> import site
>>> site.getsitepackages()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'getsitepackages'
```

**Comment by omeinusch** [comment]
Do you use Python 2.7? In this case, its a duplicate of #355 .

**Comment by wichert** [comment]
This was indeed using Python 2.7.

**Comment by zed** [comment]
`site.getsitepackages()` works on Python 2.7 and 3.2+ outside a virtualenv and I get the `AttributeError` inside a virtualenv on both Python 2 and 3.

**Comment by piotr-dobrogost** [comment]
It would be nice if any of virtualenv's maintainers took a look at this and provide some guidance as to where the problem is…

**Comment by pfmoore** [comment]
The problem (as I understand it) is that virtualenv implements its own version of ```site.py``` that doesn't track the core Python version perfectly (that's the issue behind #355, referenced above - if you follow that link, and the link to the various issues linked from there, you'll get the background).

Fixing this isn't as simple as "sync up to the core ```site.py```", because we need to support multiple Python versions, and ```site.py``` has changed between them.

Hope that helps - I'm replying as a virtualenv maintainer offering some guidance, but it's not something I'm planning on working on myself. As usual, patches welcome, but anyone willing to take this on should be clear on the amount of testing effort involved. For example, technically I believe we still support Python 2.6, so do we need to make sure that ```site.getsitepackages()``` is unavailable on that version? (IMO, no, we should just drop support for 2.6, but I wish it were that simple :smile:)

**Comment by maludwig** [comment]
I've gotten this issue on Python 3.7.0, Windows 10, in a virtualenv.

As a workaround that seems to be holding, outside of the virtualenv, I did:
```
python

Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import site
>>> site.getsitepackages()
['C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37', 'C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages']
```

Then I simply edited the site.py in my virtualenv, and added the missing function:
```

def getsitepackages():
    return ['C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37', 'C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages']

```

It's a hacky workaround, but hopefully this helps someone else.

**Comment by fabiencelier** [comment]
Same problem with Windows 10 and Python 3.7
Seems to be cause by [pywin32==226](https://github.com/pypa/pipenv/issues/3824#issuecomment-552492537)

**Comment by fahrul08** [comment]
> I've gotten this issue on Python 3.7.0, Windows 10, in a virtualenv.
> 
> As a workaround that seems to be holding, outside of the virtualenv, I did:
> 
> ```
> python
> 
> Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import site
> >>> site.getsitepackages()
> ['C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37', 'C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages']
> ```
> 
> Then I simply edited the site.py in my virtualenv, and added the missing function:
> 
> ```
> 
> def getsitepackages():
>     return ['C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37', 'C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages']
> ```
> 
> It's a hacky workaround, but hopefully this helps someone else.

It's work!

**Comment by yue327** [comment]
> I've gotten this issue on Python 3.7.0, Windows 10, in a virtualenv.
> 
> As a workaround that seems to be holding, outside of the virtualenv, I did:
> 
> ```
> python
> 
> Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import site
> >>> site.getsitepackages()
> ['C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37', 'C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages']
> ```
> 
> Then I simply edited the site.py in my virtualenv, and added the missing function:
> 
> ```
> 
> def getsitepackages():
>     return ['C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37', 'C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages']
> ```
> 
> It's a hacky workaround, but hopefully this helps someone else.

Dude this is so cool!
you made my day!

**Comment by mikemcowie** [comment]
> I've gotten this issue on Python 3.7.0, Windows 10, in a virtualenv.
> 
> As a workaround that seems to be holding, outside of the virtualenv, I did:
> 
> ```
> python
> 
> Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import site
> >>> site.getsitepackages()
> ['C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37', 'C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages']
> ```
> 
> Then I simply edited the site.py in my virtualenv, and added the missing function:
> 
> ```
> 
> def getsitepackages():
>     return ['C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37', 'C:\\Users\\maludwig\\AppData\\Local\\Programs\\Python\\Python37\\lib\\site-packages']
> ```
> 
> It's a hacky workaround, but hopefully this helps someone else.

@maludwig  - Nice. 

I'm assuming the reason virtualenv's site.py doesn't include this function is because virtualenv is supposed to keep you deliberately away from using system-wide packages? But if some package explicitly calls this function then it's inevitably going to break when trying to run in a virtualenv?

**Comment by voidspace** [comment]
I'm seeing this on multiple machines, Windows 10 Python 3.7 and 3.8. It makes virtualenv unusable unfortunately.

**Comment by okainov** [comment]
Why is this one closed? Seems still reproducible also with Python 3

**Comment by gaborbernat** [comment]
Can you post a reproducible with latest virtualenv?

**Comment by gruszczy** [comment]
I am seeing this on Mac, with virtualenv==20.0.34 and when trying to use pyre 0.0.56.

**Comment by gruszczy** [comment]
Reported also on pyre tracker: https://github.com/facebook/pyre-check/issues/326

**Comment by gaborbernat** [comment]
Can you post a reproducible with latest virtualenv?

**Comment by gaborbernat** [comment]
I want to know specifics, how you created the virtualenv, what was the output of the creation (with -vvv?), what host Python you're using?
