### ISSUE TITLE
AttributeError: module 'virtualenv.activation.python' has no attribute 'PestythonActivator'

### ISSUE THREAD

**Issue by fj-sanchez** [pypa/virtualenv#1857]
I think it's just a typo in the latest release...

**Comment by derek-bo-derek** [comment]
Definitely something wrong, this change has broken pipenv for my projects!

**Comment by pascal-de-ladurantaye** [comment]
Same, this was a breaking change in a patch version.

**Comment by andrewboss** [comment]
Likewise broke all the builds. Looks like issue identified and fixed in pull request. Lets hope it gets merged into master and built asap

**Comment by GPHemsley** [comment]
Introduced in #1855, which was merged without review and with nearly all checks failing.

**Comment by pascal-de-ladurantaye** [comment]
Should we merge the fix without a review then? ;)

**Comment by Pasha-t34** [comment]
when can we know if it gets fixed, and how can i download the new version? im trying to do a virtualenv project but i get the same error

**Comment by joekohlsdorf** [comment]
> when can we know if it gets fixed, and how can i download the new version? im trying to do a virtualenv project but i get the same error

`pip install virtualenv==20.0.21`

**Comment by brutimus** [comment]
Another confirmation of breakage from me. It broke all of my production build pipelines.

**Comment by tarp20** [comment]
I have the same issue 

anybody fixed it ?

**Comment by pascal-de-ladurantaye** [comment]
I want to blame pipenv for failing to freeze its dependencies but that was a patch version (still, pipenv should freeze its dependencies)

**Comment by minhio** [comment]
Can we just rename PythonActivator to PestythonActivator? That just sounds better IMO

**Comment by d-demirci** [comment]
pip uninstall virtualenv==20.0.22
pip install virtualenv==20.0.21

it is ok for now for me

**Comment by GPHemsley** [comment]
> Use `pip install virtualenv==20.0.21` to return to the previous version.

To future-proof, I'd recommend `pip install 'virtualenv!=20.0.22'`.

**Comment by josephong** [comment]
🐛🐍

**Comment by Pasha-t34** [comment]
> I have the same issue
> 
> anybody fixed it ?

the reply from joekohlsdorf helps a lot

**Comment by Cheukting** [comment]
> pip uninstall virtualenv==20.0.22
> pip install virtualenv==20.0.21
> 
> it is ok for now for me

My broken built is on the Travis side, it runs tox, is there a way to pin the virtualenv version in that case?

**Comment by Cheukting** [comment]
Seems the devs fixed it now, panic over.

**Comment by gaborbernat** [comment]
So sorry, messed up that release earlier (🤦), should be all fine now with ``20.0.23``.

**Comment by fernandochimi-noverde** [comment]
Version `20.0.23` works fine :+1:

**Comment by jsbueno** [comment]
"leftpad grade issue" :-(

**Comment by petergaultney** [comment]
> I want to blame pipenv for failing to freeze its dependencies but that was a patch version (still, pipenv should freeze its dependencies)

ahh, the irony.
