### ISSUE TITLE
Can't create virtual environments using Python 3.0.1

### ISSUE THREAD

**Issue by tsroten** [pypa/virtualenv#381]
First, let me say that the problem is most likely user error. I'm rather new to using Python and virtualenv. If you could help in any way, even if just to point me in the right direction, that would be great.

I'm trying to setup a virtualenv for Python 3.0.1 for testing a module I wrote. virtualenv works on my system with Python 2.6-3.3, minus 3.0. Below is the traceback and errors I see.

```
Traceback (most recent call last):
  File "setup.py", line 240, in <module>
    scripts = scripts,
  File "/Users/tsr/.pythonz/pythons/CPython-3.0.1/lib/python3.0/distutils/core.py", line 135, in setup
    ok = dist.parse_command_line()
  File "/private/var/folders/4r/99792l2s55588nfqrzcck8sw0000gn/T/tmpy4Qo9u/distribute-0.6.31/build/src/setuptools/dist.py", line 232, in parse_command_line
    result = _Distribution.parse_command_line(self)
  File "/Users/tsr/.pythonz/pythons/CPython-3.0.1/lib/python3.0/distutils/dist.py", line 441, in parse_command_line
    if self.handle_display_options(option_order):
  File "/private/var/folders/4r/99792l2s55588nfqrzcck8sw0000gn/T/tmpy4Qo9u/distribute-0.6.31/build/src/setuptools/dist.py", line 673, in handle_display_options
    sys.stdout.detach(), 'utf-8', errors, newline, line_buffering)
AttributeError: 'TextIOWrapper' object has no attribute 'detach'
Something went wrong during the installation.
See the error message above.
----------------------------------------
...Installing distribute...done.
Traceback (most recent call last):
  File "/usr/local/lib/python3.3/site-packages/virtualenv.py", line 2560, in <module>
    main()
  File "/usr/local/lib/python3.3/site-packages/virtualenv.py", line 964, in main
    never_download=options.never_download)
  File "/usr/local/lib/python3.3/site-packages/virtualenv.py", line 1071, in create_environment
    search_dirs=search_dirs, never_download=never_download)
  File "/usr/local/lib/python3.3/site-packages/virtualenv.py", line 616, in install_distribute
    search_dirs=search_dirs, never_download=never_download)
  File "/usr/local/lib/python3.3/site-packages/virtualenv.py", line 583, in _install_req
    cwd=cwd)
  File "/usr/local/lib/python3.3/site-packages/virtualenv.py", line 1042, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/tsr/.virtualenvs/test/bin/python30 -c "#!python
\"\"\"Bootstra...   sys.exit(main())
" failed with error code 2
```

**Comment by hugovk** [comment]
This is old issue can be closed now because EOL Python 3.0 was dropped a long time ago.

**Comment by tsroten** [comment]
Agreed, closing.
